---
version: 2.1

executors:
  go-build:
    docker:
      - image: cimg/go:1.15

commands:
  # commands to persist and load CIRCLE_BUILD_NUM across jobs
  save-build-num:
    steps:
      - run: echo "export CIRCLE_BUILD_NUM=$CIRCLE_BUILD_NUM" > circle-build-num
  load-build-num:
    steps:
      - run: cat circle-build-num >> $BASH_ENV

  # go.mod caching
  save-go-mod-cache:
    steps:
      - save_cache:
          key: v3-dependencies-{{ checksum "go.sum" }}
          paths:
            - /go/pkg/mod
            - /home/circleci/go/pkg/mod
  restore-go-mod-cache:
    steps:
      - restore_cache:
          keys:
            - v3-dependencies-{{ checksum "go.sum" }}

  # save / load workspace
  save-workspace:
    steps:
      - persist_to_workspace:
          root: .
          paths:
            - ./
  restore-workspace:
    steps:
      - attach_workspace:
          at: .

jobs:
  build:
    executor: go-build
    steps:
      - checkout
      - restore-go-mod-cache
      - save-build-num
      - run: make build-release
      - save-go-mod-cache
      - save-workspace

  push-release:
    executor: go-build
    steps:
      - restore-workspace
      - load-build-num
      - run: make push-release

  push-docker:
    executor: go-build
    steps:
      - setup_remote_docker
      - restore-workspace
      - load-build-num
      - run: docker login -u "$QUAY_USER" -p "$QUAY_PASSWD" quay.io
      - run: make build-docker
      - run: make push-docker

workflows:
  version: 2
  run:
    jobs:
      - build
      - push-release:
          requires:
            - build
          filters:
            branches:
              only:
                - master
      - push-docker:
          requires:
            - build
          filters:
            branches:
              only:
                - master

